// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLXueiMiH_cLvI_tBklO8SO6jGTqiL99M',
    appId: '1:816982077331:web:cbf82216566b444a044266',
    messagingSenderId: '816982077331',
    projectId: 'quickfix-a050e',
    authDomain: 'quickfix-a050e.firebaseapp.com',
    storageBucket: 'quickfix-a050e.firebasestorage.app',
    measurementId: 'G-JTE4WVGH49',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJJQlPwmB6uHCn3_rqKFOx9kuKg2O50P0',
    appId: '1:816982077331:android:aef2e9491393d657044266',
    messagingSenderId: '816982077331',
    projectId: 'quickfix-a050e',
    storageBucket: 'quickfix-a050e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIoAzFSqcTW5Xk6U-eoht4JoMY7-fNh1o',
    appId: '1:816982077331:ios:21eaac8a778d6453044266',
    messagingSenderId: '816982077331',
    projectId: 'quickfix-a050e',
    storageBucket: 'quickfix-a050e.firebasestorage.app',
    iosBundleId: 'com.example.civicapp',
  );
}
